AWSTemplateFormatVersion: 2010-09-09
Description: Sets Up ECS Alarms
Parameters:
  ClusterName:
    Type: String

  AppName:
    Type: String

  EcsAlarmIncreaseCpuUtilizationOperator:
    Type: String
    Default: GreaterThanThreshold

  EcsAlarmIncreaseCpuUtilizationThreshold:
    Type: String
    Default: 80

  EcsAlarmIncreaseCpuUtilizationSeconds:
    Type: String
    Default: 60

  EcsAlarmDecreaseCpuUtilizationOperator:
    Type: String
    Default: LessThanThreshold

  EcsAlarmDecreaseCpuUtilizationThreshold:
    Type: String
    Default: 20

  EcsAlarmDecreaseCpuUtilizationSeconds:
    Type: String
    Default: 300

Resources:
  EcsAlarmIncreaseCpuUtilization:
    Type: AWS::CloudWatch::Alarm
    Properties:
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      EvaluationPeriods: 1
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            'Fn::ImportValue': !Sub ${ClusterName}-AutoScalingGroup
      AlarmActions:
        - 'Fn::ImportValue': !Sub ${ClusterName}-${AppName}-WebEcsScaleOut
      AlarmName: !Sub ecs_alarm_increase_cpuutilization-${AppName}
      Period: !Ref EcsAlarmIncreaseCpuUtilizationSeconds
      ComparisonOperator: !Ref EcsAlarmIncreaseCpuUtilizationOperator
      Statistic: Average
      Threshold: !Ref EcsAlarmIncreaseCpuUtilizationThreshold

  EcsAlarmDecreaseCpuUtilization:
    Type: AWS::CloudWatch::Alarm
    Properties:
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      EvaluationPeriods: 1
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            'Fn::ImportValue': !Sub ${ClusterName}-AutoScalingGroup
      AlarmActions:
        - 'Fn::ImportValue': !Sub ${ClusterName}-${AppName}-WebEcsScaleIn
      AlarmName: !Sub ecs_alarm_decrease_cpuutilization-${AppName}
      Period: !Ref EcsAlarmDecreaseCpuUtilizationSeconds
      ComparisonOperator: !Ref EcsAlarmDecreaseCpuUtilizationOperator
      Statistic: Average
      Threshold: !Ref EcsAlarmDecreaseCpuUtilizationThreshold