AWSTemplateFormatVersion: 2010-09-09
Description: Sets up ecs cluster alarms
Parameters:
  ClusterName:
    Description: Cluster name
    Type: String

  ASGAlarmIncreaseCPUUtilizationSeconds:
    Type: Number
    Default: 60

  ASGAlarmIncreaseCPUUtilizationOperator:
    Type: String
    Default: GreaterThanOrEqualToThreshold

  ASGAlarmIncreaseCPUUtilizationThreshold:
    Type: Number
    Default: 80

  ASGAlarmDecreaseCPUUtilizationSeconds:
    Type: Number
    Default: 300

  ASGAlarmDecreaseCPUUtilizationOperator:
    Type: String
    Default: LessThanOrEqualToThreshold

  ASGAlarmDecreaseCPUUtilizationThreshold:
    Type: Number
    Default: 20

Resources:
  ASGAlarmIncreaseCPUUtilization:
    Type: AWS::CloudWatch::Alarm
    Properties:
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      EvaluationPeriods: 1
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Fn::ImportValue: !Sub ${ClusterName}-AutoScalingGroup
      AlarmActions:
        - Fn::ImportValue: !Sub ${ClusterName}-ScaleUpPolicy
      AlarmName: !Sub ${ClusterName}_cluster__asg_alarm_increase_cpuutilization
      Period: !Ref ASGAlarmIncreaseCPUUtilizationSeconds
      ComparisonOperator: !Ref ASGAlarmIncreaseCPUUtilizationOperator
      Statistic: Average
      Threshold: !Ref ASGAlarmIncreaseCPUUtilizationThreshold

  ASGAlarmDecreaseCPUUtilization:
    Type: AWS::CloudWatch::Alarm
    Properties:
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      EvaluationPeriods: 1
      Dimensions:
        - Name: AutoScalingGroupName
          Value:
            Fn::ImportValue: !Sub ${ClusterName}-AutoScalingGroup
      AlarmActions:
        - Fn::ImportValue: !Sub ${ClusterName}-ScaleDownPolicy
      AlarmName: !Sub ${ClusterName}_cluster__asg_alarm_decrease_cpuutilization
      Period: !Ref ASGAlarmDecreaseCPUUtilizationSeconds
      ComparisonOperator: !Ref ASGAlarmDecreaseCPUUtilizationOperator
      Statistic: Average
      Threshold: !Ref ASGAlarmDecreaseCPUUtilizationThreshold
